### ISSUE TITLE
Testing Failure

### ISSUE THREAD

**Issue by Sivaumasuthan** [rajurayhan/learning-anugular#1]
Hi Developers,

Thanks it is good application running without error.
So glad you people made simple and working applications.
I also try to do the unit and e2e testing, where  I am getting failure, will you please fix those.

**Comment by rajurayhan** [comment]
Hello @Sivaumasuthan ,
Thanks for using this repo. 

But I'm sorry that I haven't been updating it for a long time as it was a Learning Project for me. I tried to implement what i learnt so that i can reuse it in future. And there won't be any update available for this repo. 

Regards,
